version: "3"
services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: SPIGOT
      VERSION: "1.19.1"
      OPS: "cog25,june2dg"
    volumes:
      - ./data-minecraft:/data
    restart: always
    
  webdav:
    container_name: mcwebdav
    image: derkades/webdav
    volumes:
      - ./data-mc:/data
    environment:
      - USERNAME=${WD_USERNAME}
      - PASSWORD=${WD_PASSWORD}
      - TZ=Asia/Seoul
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mcwebdav.rule=Host(`mcwd.cog.city`)"
      - "traefik.http.middlewares.mcwebdav.redirectscheme.scheme=https"
      - "traefik.http.middlewares.mcwebdav.redirectscheme.permanent=true"



  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.10
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      WEBSOCKET_ENABLED: "true"  # Enable WebSocket notifications.
      
    volumes:
      - ./data-vw:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`vw.cog.city`)"
      - "traefik.http.middlewares.vaultwarden.redirectscheme.scheme=https"
      - "traefik.http.middlewares.vaultwarden.redirectscheme.permanent=true"

